-- ============================================================
-- reviews : aggregate root + queue owner (single source of truth for status)
-- ============================================================
CREATE TABLE reviews (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT       NOT NULL,
    merge_request_id  BIGINT       NOT NULL,          -- MR IID
    head_sha          VARCHAR(64)  NOT NULL,
    base_sha          VARCHAR(64)  NOT NULL,
    prompt_version    VARCHAR(32)  NOT NULL,
    status            VARCHAR(16)  NOT NULL
        CONSTRAINT ck_reviews_status CHECK (status IN
            ('NEW','QUEUED','RUNNING','COMPLETED','PUBLISHED','FAILED','CANCELLED','OBSOLETE')),
    priority          INTEGER      NOT NULL DEFAULT 10,
    attempts          INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Dedup: at most ONE active review per (project, MR, head_sha).
-- Active = the 5 statuses that block a new review (req. 1.5). Enforced at DB level;
-- concurrent create -> unique violation -> app returns the existing reviewId.
CREATE UNIQUE INDEX ux_reviews_dedup_active
    ON reviews (project_id, merge_request_id, head_sha)
    WHERE status IN ('NEW','QUEUED','RUNNING','COMPLETED','PUBLISHED');

-- Queue claim: priority DESC, created_at ASC over QUEUED rows.
CREATE INDEX ix_reviews_queue
    ON reviews (priority DESC, created_at ASC)
    WHERE status = 'QUEUED';

-- OBSOLETE sweep when a new head_sha arrives for the same MR.
CREATE INDEX ix_reviews_mr ON reviews (project_id, merge_request_id);

-- Publish-retry candidate scan.
CREATE INDEX ix_reviews_status ON reviews (status);

-- ============================================================
-- review_inputs : immutable payload (enables re-run without GitLab, req. 1.2/4.3)
-- ============================================================
CREATE TABLE review_inputs (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id         BIGINT       NOT NULL UNIQUE
        REFERENCES reviews (id) ON DELETE CASCADE,
    diff              TEXT         NOT NULL,
    prompt_version    VARCHAR(32)  NOT NULL,
    head_sha          VARCHAR(64)  NOT NULL,
    base_sha          VARCHAR(64)  NOT NULL,
    estimated_tokens  INTEGER,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ============================================================
-- backends : llama-server registry
-- ============================================================
CREATE TABLE backends (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64)  NOT NULL UNIQUE,          -- e.g. "mac-mini-01" (worker sends this)
    url         VARCHAR(256) NOT NULL,
    model       VARCHAR(128) NOT NULL,
    capacity    INTEGER      NOT NULL DEFAULT 1,
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
        CONSTRAINT ck_backends_status CHECK (status IN
            ('ACTIVE','SUSPECT','MAINTENANCE','OFFLINE')),
    last_seen   TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ============================================================
-- review_jobs : current execution record (1:1 with reviews)
-- No status/priority here -> reviews is the sole status owner.
-- ============================================================
CREATE TABLE review_jobs (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id     BIGINT       NOT NULL UNIQUE
        REFERENCES reviews (id) ON DELETE CASCADE,
    backend_id    BIGINT       REFERENCES backends (id),
    worker_id     VARCHAR(64),
    heartbeat_at  TIMESTAMPTZ,
    claimed_at    TIMESTAMPTZ,
    started_at    TIMESTAMPTZ,
    finished_at   TIMESTAMPTZ,
    last_error    TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Capacity count (running jobs per backend) + timeout sweep.
CREATE INDEX ix_jobs_backend    ON review_jobs (backend_id);
CREATE INDEX ix_jobs_heartbeat  ON review_jobs (heartbeat_at);

-- ============================================================
-- review_results : raw model response (stored BEFORE parsing) + metrics
-- ============================================================
CREATE TABLE review_results (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id          BIGINT       NOT NULL UNIQUE
        REFERENCES reviews (id) ON DELETE CASCADE,     -- UNIQUE => idempotent result
    raw_response       TEXT         NOT NULL,          -- mandatory (req. 1.9)
    summary            TEXT,
    prompt_tokens      INTEGER,
    completion_tokens  INTEGER,
    total_tokens       INTEGER,
    duration_ms        BIGINT,
    model              VARCHAR(128),
    backend_id         BIGINT       REFERENCES backends (id),
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ============================================================
-- review_comments : parsed comments + idempotent publish tracking
-- ============================================================
CREATE TABLE review_comments (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id      BIGINT       NOT NULL
        REFERENCES reviews (id) ON DELETE CASCADE,
    file_path      VARCHAR(1024),
    line_number    INTEGER,
    severity       VARCHAR(16)
        CONSTRAINT ck_comment_severity CHECK (severity IN ('INFO','MINOR','MAJOR','CRITICAL')),
    comment        TEXT         NOT NULL,
    discussion_id  VARCHAR(128),                       -- GitLab discussion id, set after publish
    published_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Publish-retry: fetch only not-yet-published comments of a review.
CREATE INDEX ix_comments_unpublished
    ON review_comments (review_id)
    WHERE published_at IS NULL;

-- ============================================================
-- review_events : append-only audit trail
-- ============================================================
CREATE TABLE review_events (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id   BIGINT       NOT NULL
        REFERENCES reviews (id) ON DELETE CASCADE,
    event_type  VARCHAR(32)  NOT NULL
        CONSTRAINT ck_event_type CHECK (event_type IN
            ('CREATED','CLAIMED','RUNNING','HEARTBEAT','RETRY',
             'COMPLETED','PUBLISHED','FAILED','OBSOLETE','CANCELLED')),
    worker_id   VARCHAR(64),
    backend_id  BIGINT,
    details     TEXT,                                  -- free text / JSON, NEVER secrets
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_events_review ON review_events (review_id, created_at);
