-- ============================================================
-- V2: diff chunking support.
--
-- Moves queue ownership from `reviews` (1:1 with review_jobs, V1) to `review_jobs` (1:N per
-- review, one row per diff chunk). `reviews.status` becomes a value DERIVED from its children's
-- job statuses (see ChunkCoordinator) rather than the queue-claim target itself.
--
-- FORWARD-ONLY: see DEPLOYMENT.md "V2 migration" section for the full rollback-hazard writeup and
-- the recommended <150s deploy-downtime budget. In short: rolling back the JAR after this migration
-- has run would let the old review-level claim query re-claim in-flight chunk jobs and double-execute
-- them, since the old code never looks at review_jobs.status at all.
--
-- Ordinary transactional DDL throughout (no CREATE INDEX CONCURRENTLY) so this runs inside Flyway's
-- single migration transaction.
-- ============================================================

-- ============================================================
-- review_chunks : one row per diff chunk (file-based split of review_inputs.diff)
-- ============================================================
CREATE TABLE review_chunks (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id         BIGINT       NOT NULL
        REFERENCES reviews (id) ON DELETE CASCADE,
    chunk_index       INTEGER      NOT NULL,
    chunk_count       INTEGER      NOT NULL,
    diff              TEXT         NOT NULL,
    estimated_tokens  INTEGER,
    file_count        INTEGER,
    file_paths        TEXT,                          -- JSON array of SANITIZED paths (CSR-09/CSR-10)
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_review_chunks_review_index UNIQUE (review_id, chunk_index),
    CONSTRAINT ck_review_chunks_index CHECK (chunk_index >= 0 AND chunk_index < chunk_count),
    CONSTRAINT ck_review_chunks_count CHECK (chunk_count >= 1)
);

-- (review_id, chunk_index) unique index above already serves plain review_id lookups (leftmost column).

-- ============================================================
-- review_jobs : becomes the queue owner (1:N per review). Drop the old implicit UNIQUE(review_id)
-- from V1 first -- looked up dynamically rather than assuming Postgres's default naming, since the
-- exact auto-generated name depends on how the column was declared (JPA vs raw DDL) and this must be
-- safe to run against either.
-- ============================================================
DO $$
DECLARE
    found_constraint text;
BEGIN
    SELECT tc.constraint_name INTO found_constraint
    FROM information_schema.table_constraints tc
    JOIN information_schema.constraint_column_usage ccu
      ON tc.constraint_name = ccu.constraint_name AND tc.table_schema = ccu.table_schema
    WHERE tc.table_schema = 'public'
      AND tc.table_name = 'review_jobs'
      AND tc.constraint_type = 'UNIQUE'
      AND ccu.column_name = 'review_id'
    LIMIT 1;

    IF found_constraint IS NOT NULL THEN
        EXECUTE format('ALTER TABLE review_jobs DROP CONSTRAINT IF EXISTS %I', found_constraint);
    END IF;
END $$;

ALTER TABLE review_jobs
    ADD COLUMN chunk_id    BIGINT REFERENCES review_chunks (id),
    ADD COLUMN chunk_index INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN status      VARCHAR(16),               -- nullable until backfilled below, then locked NOT NULL
    ADD COLUMN priority    INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN attempts    INTEGER NOT NULL DEFAULT 0;

-- ---- Backfill (review_jobs.id preserved for every in-flight row -- UPDATE only, never delete+reinsert) ----

-- 1) A chunk_index=0/chunk_count=1 row for every review that doesn't have one yet, sourced from that
--    review's immutable review_inputs.diff (covers every review regardless of status -- both the ones
--    that already have a review_jobs row and the ones that were never claimed).
INSERT INTO review_chunks (review_id, chunk_index, chunk_count, diff, estimated_tokens, created_at)
SELECT r.id, 0, 1, ri.diff, ri.estimated_tokens, now()
FROM reviews r
JOIN review_inputs ri ON ri.review_id = r.id
WHERE NOT EXISTS (SELECT 1 FROM review_chunks rc WHERE rc.review_id = r.id);

-- 2) A review_jobs row for every review that was never claimed (no existing job row) -- e.g. still
--    NEW/QUEUED, or CANCELLED/OBSOLETE before ever being claimed.
INSERT INTO review_jobs (review_id, chunk_id, chunk_index, status, priority, attempts, created_at, updated_at)
SELECT r.id, rc.id, 0,
       CASE r.status
           WHEN 'NEW' THEN 'QUEUED'
           WHEN 'PUBLISHED' THEN 'COMPLETED'
           ELSE r.status
       END,
       r.priority, r.attempts, now(), now()
FROM reviews r
JOIN review_chunks rc ON rc.review_id = r.id AND rc.chunk_index = 0
WHERE NOT EXISTS (SELECT 1 FROM review_jobs j WHERE j.review_id = r.id);

-- 3) Derive status/priority/attempts and link chunk_id on every EXISTING job row (in-flight RUNNING
--    rows included -- this is an UPDATE, so review_jobs.id is untouched).
UPDATE review_jobs j
SET chunk_id = rc.id,
    status = CASE r.status
        WHEN 'NEW' THEN 'QUEUED'
        WHEN 'PUBLISHED' THEN 'COMPLETED'
        ELSE r.status
    END,
    priority = r.priority,
    attempts = r.attempts
FROM reviews r
JOIN review_chunks rc ON rc.review_id = r.id AND rc.chunk_index = 0
WHERE j.review_id = r.id
  AND j.status IS NULL;

ALTER TABLE review_jobs ALTER COLUMN status SET NOT NULL;
ALTER TABLE review_jobs ADD CONSTRAINT ck_review_jobs_status CHECK (status IN
    ('QUEUED','RUNNING','COMPLETED','FAILED','CANCELLED','OBSOLETE'));

CREATE UNIQUE INDEX uq_review_jobs_review_chunk ON review_jobs (review_id, chunk_index);

-- Claim query: priority DESC, created_at ASC, chunk_index ASC over QUEUED rows only.
CREATE INDEX ix_review_jobs_queue
    ON review_jobs (priority DESC, created_at ASC, chunk_index ASC)
    WHERE status = 'QUEUED';

-- Heartbeat sweep: RUNNING rows only.
CREATE INDEX ix_review_jobs_heartbeat_running
    ON review_jobs (heartbeat_at)
    WHERE status = 'RUNNING';

-- Backend capacity counting: RUNNING rows per backend only.
CREATE INDEX ix_review_jobs_backend_running
    ON review_jobs (backend_id)
    WHERE status = 'RUNNING';

-- ============================================================
-- review_results : becomes 1:N per review (one row per completed chunk).
-- ============================================================
DO $$
DECLARE
    found_constraint text;
BEGIN
    SELECT tc.constraint_name INTO found_constraint
    FROM information_schema.table_constraints tc
    JOIN information_schema.constraint_column_usage ccu
      ON tc.constraint_name = ccu.constraint_name AND tc.table_schema = ccu.table_schema
    WHERE tc.table_schema = 'public'
      AND tc.table_name = 'review_results'
      AND tc.constraint_type = 'UNIQUE'
      AND ccu.column_name = 'review_id'
    LIMIT 1;

    IF found_constraint IS NOT NULL THEN
        EXECUTE format('ALTER TABLE review_results DROP CONSTRAINT IF EXISTS %I', found_constraint);
    END IF;
END $$;

ALTER TABLE review_results
    ADD COLUMN chunk_index INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN job_id      BIGINT REFERENCES review_jobs (id);

-- Best-effort backfill: link each existing result row to its (single, chunk_index=0) job row.
UPDATE review_results res
SET job_id = j.id
FROM review_jobs j
WHERE j.review_id = res.review_id
  AND j.chunk_index = res.chunk_index
  AND res.job_id IS NULL;

CREATE UNIQUE INDEX uq_review_results_review_chunk ON review_results (review_id, chunk_index);

-- ============================================================
-- review_comments : chunk_index is audit/debug only, no constraint.
-- ============================================================
ALTER TABLE review_comments ADD COLUMN chunk_index INTEGER;

-- ============================================================
-- review_events : chunk_index/job_id are audit/debug only, no constraint. No new EventType values --
-- the existing CLAIMED/RUNNING/HEARTBEAT/RETRY/COMPLETED/FAILED/CANCELLED events become per-chunk-job
-- using these columns; the chunk count is recorded in the existing CREATED event's `details` field
-- (e.g. "chunks=6").
-- ============================================================
ALTER TABLE review_events ADD COLUMN chunk_index INTEGER;
ALTER TABLE review_events ADD COLUMN job_id BIGINT;
