-- ============================================================
-- V3: Prompt Manager (architecture §6, docs/prompt-manager-architecture.md).
--
-- New table `review_prompt_sections` (immutable, per-section provenance -- MULTI format needs
-- sections as separate entities, not split-by-delimiter of a blob; provenance is per-source, and
-- there are two distinct sources with two distinct SHAs). Plus three ALTERs threading the feature
-- through the existing lifecycle tables.
--
-- Ordinary transactional DDL throughout (no CREATE INDEX CONCURRENTLY) so this runs inside Flyway's
-- single migration transaction, matching V1/V2.
-- ============================================================

CREATE TABLE review_prompt_sections (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id         BIGINT       NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
    ordinal           INTEGER      NOT NULL,
    kind              VARCHAR(32)  NOT NULL
        CONSTRAINT ck_prompt_section_kind CHECK (kind IN
            ('CORPORATE_BASE','CORPORATE_REVIEW_RULES','PROJECT_ARCHITECTURE','PROJECT_CODE_RULES')),
    status            VARCHAR(16)  NOT NULL DEFAULT 'PRESENT'
        CONSTRAINT ck_prompt_section_status CHECK (status IN ('PRESENT','ABSENT')),  -- PMR-11
    content           TEXT         NOT NULL DEFAULT '',   -- empty for ABSENT rows
    source_project    VARCHAR(256) NOT NULL,
    source_path       VARCHAR(512) NOT NULL,
    source_ref        VARCHAR(256) NOT NULL,
    source_commit     VARCHAR(64)  NOT NULL,
    content_sha256    VARCHAR(64)  NOT NULL,
    estimated_tokens  INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_prompt_sections_review_ordinal UNIQUE (review_id, ordinal),
    CONSTRAINT uq_prompt_sections_review_kind    UNIQUE (review_id, kind)          -- PMR-04/PMR-08
);

-- (review_id, ordinal) unique index above already serves claim-time "all sections of one review" reads.

ALTER TABLE review_inputs
    ADD COLUMN system_prompt_tokens INTEGER,
    ADD COLUMN prompt_degraded      BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE reviews
    ADD COLUMN prompt_bundle_mode VARCHAR(16) NOT NULL DEFAULT 'NONE'
        CONSTRAINT ck_reviews_prompt_bundle_mode CHECK (prompt_bundle_mode IN ('NONE','REPO'));  -- PMR-09

ALTER TABLE backends
    ADD COLUMN prompt_message_format VARCHAR(16)
        CONSTRAINT ck_backends_prompt_message_format
        CHECK (prompt_message_format IS NULL OR prompt_message_format IN ('MULTI','SINGLE'));

-- PMR-07: the app DB user must get INSERT/SELECT only on review_prompt_sections (no UPDATE/DELETE) --
-- see DEPLOYMENT.md's GRANT block, extends the same append-only contract already applied to
-- review_events (SR-19). Not expressed here because V1/V2 never GRANT from inside Flyway either
-- (the migration runs as the schema-owning role, not the constrained app role).
