-- Backend Self-Registration & Backend Admin API (docs/backend-self-registration-architecture.md §8,
-- docs/backend-self-registration-threat-model.md BSQ-01/BSQ-22).
--
-- One additive nullable column, no constraint changes, no backfill -- rollback-tolerant like V4/V5: an
-- older JAR ignores the column (Hibernate ddl-auto: validate does not fail on an extra DB column, and
-- an older JAR never writes it).
SET lock_timeout = '5s';

-- announced_by: the workerId of the Worker that currently holds self-registration of this row.
-- NULL = unclaimed (registered by an admin, by raw SQL, or released by an admin write -- see
-- BackendRegistryService#upsertByAdmin). A misconfiguration guard, never an authorization boundary
-- (workerId is a self-declared claim under the shared WORKER token -- BSQ-10, T-03/T-15/WT-16).
ALTER TABLE backends
    ADD COLUMN announced_by VARCHAR(64);

-- BSQ-22/BST-16 (deployment note, not a Flyway-managed change -- this project does not let Flyway
-- manage GRANTs): this feature introduces the Gateway application role's first INSERT into `backends`
-- (previously the role only ever UPDATEd it, via BackendHealthChecker). DEPLOYMENT.md's GRANT block
-- already lists INSERT table-level, so announced_by is covered automatically and no sequence grant is
-- needed (backends.id is GENERATED BY DEFAULT AS IDENTITY) -- but this must be VERIFIED against the
-- actually-deployed role rather than assumed, since roles drift over time and the architecture doc's
-- original claim ("INSERT was never granted") turned out to be false against this repo's own
-- DEPLOYMENT.md.
--
-- The documented grant is also WIDER than this feature needs: DELETE on `backends` is currently granted
-- but no code path in this feature (or anywhere else) ever deletes a backend row -- §5's "hard delete
-- cannot be offered" (review_jobs/review_results FK backends(id) with no ON DELETE) is enforced by
-- application code alone today. Revoking DELETE (`REVOKE DELETE ON backends FROM <gateway_role>;`) is a
-- recommended, SHOULD-level (BSQ-21), out-of-band DB hardening step for an operator to apply -- not
-- something this migration does automatically (Flyway does not manage GRANTs/REVOKEs in this project).
